/**
 * OData capability registry — audited 2026-06-19 against moskovskiy instance.
 * Generated by probing each entity with $top=0 and recording HTTP status.
 *
 * Usage: check `CAPABILITIES[entity].odata` before recommending a tool that
 * queries that entity, or pass to ToolDiscoveryService to filter bad endpoints.
 */

export interface EntityCapability {
  odata: boolean;
  slowOdata?: boolean;   // exists but consistently >10s — apply higher timeout
  knownIssues?: string[];
  correctName?: string;  // when a wrong name was used in code and has been fixed
}

export const CAPABILITIES: Record<string, EntityCapability> = {

  // ─── Accumulation Registers ───────────────────────────────────────────────
  "AccumulationRegister_ТоварыОрганизацийБУ": { odata: true },
  "AccumulationRegister_ВзаиморасчетыОрганизацийСКонтрагентамиФизЛицами": { odata: true },

  // Mutual settlements (legal entities) — not exposed in this deployment
  "AccumulationRegister_ВзаиморасчетыСКонтрагентами": {
    odata: false,
    knownIssues: ["404 in moskovskiy — use AccountingRegister_Типовой/BalanceAndTurnovers on accounts 1210/3310 instead"],
  },
  "AccumulationRegister_ВзаиморасчетыОрганизацийСКонтрагентами": {
    odata: false,
    knownIssues: ["404 in moskovskiy — use AccountingRegister_Типовой/BalanceAndTurnovers on accounts 1210/3310 instead"],
  },

  // Payroll / cash accumulation registers — not in this OData schema
  "AccumulationRegister_РасчетыСПерсоналомОрганизаций": {
    odata: false,
    knownIssues: ["404 — payroll balances via AccountingRegister account 3350 instead"],
  },
  "AccumulationRegister_ДенежныеСредства": {
    odata: false,
    knownIssues: ["404 — cash position via AccountingRegister accounts 1010/1030 instead"],
  },
  "AccumulationRegister_ДенежныеСредстваОрганизаций": {
    odata: false,
    knownIssues: ["404 — cash position via AccountingRegister accounts 1010/1030 instead"],
  },
  "AccumulationRegister_ЗарплатаКВыплатеОрганизаций": { odata: false },
  "AccumulationRegister_НачисленияИВыплатыПоЗарплате": { odata: false },
  "AccumulationRegister_НачисленияПоЕСН": { odata: false },
  "AccumulationRegister_РасчетыСПокупателями": { odata: false },
  "AccumulationRegister_РасчетыСПоставщиками": { odata: false },

  // ─── Accounting Register ──────────────────────────────────────────────────
  "AccountingRegister_Типовой": { odata: true },
  "AccountingRegister_Типовой_RecordType": { odata: true },
  // Virtual tables: BalanceAndTurnovers is fast; Balance/Turnovers are slow (>20s)
  "AccountingRegister_Типовой/BalanceAndTurnovers": { odata: true },
  "AccountingRegister_Типовой/Balance": {
    odata: true,
    slowOdata: true,
    knownIssues: ["Response time >20s — always use with tight $filter on period and account"],
  },
  "AccountingRegister_Типовой/Turnovers": {
    odata: true,
    slowOdata: true,
    knownIssues: ["Response time >20s — always use with tight $filter on period and account"],
  },

  // ─── Catalogs ─────────────────────────────────────────────────────────────
  "Catalog_Контрагенты": { odata: true, slowOdata: true },
  "Catalog_Организации": { odata: true },
  "Catalog_Номенклатура": { odata: true },
  "Catalog_Склады": { odata: true },
  "Catalog_ФизическиеЛица": { odata: true },
  "Catalog_ДоговорыКонтрагентов": { odata: true },
  "Catalog_СотрудникиОрганизаций": {
    odata: true,
    knownIssues: ["Previously referenced as Catalog_Сотрудники (404) — fixed 2026-06-19"],
  },
  "Catalog_Сотрудники": {
    odata: false,
    correctName: "Catalog_СотрудникиОрганизаций",
    knownIssues: ["Wrong name — use Catalog_СотрудникиОрганизаций"],
  },

  // ─── Documents ────────────────────────────────────────────────────────────
  "Document_ПлатежноеПоручениеВходящее": { odata: true },
  "Document_ПлатежноеПоручениеИсходящее": { odata: true },
  "Document_ПоступлениеТоваровУслуг": { odata: true },
  "Document_РеализацияТоваровУслуг": { odata: true, slowOdata: true },
  "Document_НачислениеЗарплатыРаботникамОрганизаций": { odata: true },
  "Document_АвансовыйОтчет": { odata: true },
  "Document_ПринятиеКУчетуОС": { odata: true },
  "Document_ПриходныйКассовыйОрдер": {
    odata: true,
    knownIssues: ["Previously referenced as Document_КассовыйОрдерПриходный (404) — fixed 2026-06-19"],
  },
  "Document_РасходныйКассовыйОрдер": {
    odata: true,
    knownIssues: ["Previously referenced as Document_КассовыйОрдерРасходный (404) — fixed 2026-06-19"],
  },
  // Wrong names that were in the codebase — kept for reference only
  "Document_КассовыйОрдерПриходный": {
    odata: false,
    correctName: "Document_ПриходныйКассовыйОрдер",
    knownIssues: ["Wrong name — use Document_ПриходныйКассовыйОрдер"],
  },
  "Document_КассовыйОрдерРасходный": {
    odata: false,
    correctName: "Document_РасходныйКассовыйОрдер",
    knownIssues: ["Wrong name — use Document_РасходныйКассовыйОрдер"],
  },
  "Document_СписаниеЗапасов": { odata: false },

  // ─── Information Registers ────────────────────────────────────────────────
  "InformationRegister_КурсыВалют": { odata: true, slowOdata: true },
  "InformationRegister_ЖурналПроводок": { odata: false },
};

/** Returns true if the entity is queryable via OData in the current deployment. */
export function isODataAvailable(entityName: string): boolean {
  return CAPABILITIES[entityName]?.odata === true;
}

/**
 * Returns the correct entity name if the given name is a known wrong alias,
 * or undefined if the name is already correct or unknown.
 */
export function correctEntityName(entityName: string): string | undefined {
  return CAPABILITIES[entityName]?.correctName;
}

/** Returns known issues for an entity, or empty array. */
export function getKnownIssues(entityName: string): string[] {
  return CAPABILITIES[entityName]?.knownIssues ?? [];
}
